import type { ContractSchema, SchemaMethod } from "./types";

/* Maps GenVM schema types to TypeScript and Python types. */

function tsType(type: unknown): string {
  if (typeof type === "string") {
    if (["int", "uint", "u8", "u16", "u32", "u64", "u256", "i8", "i16", "i32", "i64", "i256"].includes(type)) return "number";
    if (type === "string") return "string";
    if (type === "bool") return "boolean";
    if (type === "address") return "Address";
    if (type === "any") return "unknown";
    if (type === "null") return "null";
  }
  if (type && typeof type === "object") {
    const t = type as { $dict?: unknown; $rep?: unknown };
    if ("$dict" in t) return `Record<string, ${tsType(t.$dict)}>`;
    if ("$rep" in t) return `${tsType(t.$rep)}[]`;
  }
  return "unknown";
}

function pyType(type: unknown): string {
  if (typeof type === "string") {
    if (["int", "uint", "u8", "u16", "u32", "u64", "u256", "i8", "i16", "i32", "i64", "i256"].includes(type)) return "int";
    if (type === "string") return "str";
    if (type === "bool") return "bool";
    if (type === "address") return "str";
    if (type === "any") return "Any";
    if (type === "null") return "None";
  }
  if (type && typeof type === "object") {
    const t = type as { $dict?: unknown; $rep?: unknown };
    if ("$dict" in t) return `Dict[str, ${pyType(t.$dict)}]`;
    if ("$rep" in t) return `List[${pyType(t.$rep)}]`;
  }
  return "Any";
}

function camelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function methodParams(method: SchemaMethod): { name: string; type: unknown }[] {
  const params = Array.isArray(method.params) ? method.params : [];
  return params.map((p) => ({ name: p[0], type: p[1] }));
}

function chainImport(network: string): string {
  const map: Record<string, string> = {
    studionet: "studionet",
    "testnet-bradbury": "testnetBradbury",
    "testnet-asimov": "testnetAsimov",
    localnet: "localnet",
  };
  return map[network] || "studionet";
}

export function generateIndexTs(schema: ContractSchema, contractAddress: string, networkName: string): string {
  const methods = Object.entries(schema.methods || {});
  const chain = chainImport(networkName);

  const lines: string[] = [];
  lines.push("// Generated by GenKit — do not edit by hand.");
  lines.push(`// Source: ${contractAddress} (${networkName})`);
  lines.push('import { createClient } from "genlayer-js";');
  lines.push(`import { ${chain} } from "genlayer-js/chains";`);
  lines.push("");
  lines.push("export type Address = `0x${string}`;");
  lines.push("");
  lines.push("export interface ContractClientOptions {");
  lines.push("  endpoint?: string;");
  lines.push("  account?: Address;");
  lines.push("  provider?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export function createContractClient(opts: ContractClientOptions = {}) {");
  lines.push("  return createClient({");
  lines.push(`    chain: ${chain},`);
  lines.push("    ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),");
  lines.push("    ...(opts.account ? { account: opts.account as `0x${string}` } : {}),");
  lines.push("    ...(opts.provider ? { provider: opts.provider as never } : {}),");
  lines.push("  });");
  lines.push("}");
  lines.push("");
  lines.push(`export const CONTRACT_ADDRESS = "${contractAddress}" as const;`);
  lines.push("");
  for (const [name, method] of methods) {
    const fn = camelCase(name);
    const params = methodParams(method);
    const isWrite = method.readonly === false;
    const ret = isWrite ? "string" : tsType(method.ret);
    const paramDecl = ["client", ...params.map((p) => `${p.name}: ${tsType(p.type)}`)].join(", ");
    const argsList = params.map((p) => p.name).join(", ");
    lines.push("// ─────────────────────────────────────────────");
    lines.push(`// ${name} — ${isWrite ? "write" : "view"}`);
    lines.push(`export async function ${fn}(${paramDecl}): Promise<${ret}> {`);
    if (isWrite) {
      lines.push("  // Write methods submit a transaction and return the tx hash.");
      lines.push("  // Wait for finality with: await client.waitForTransactionReceipt({ hash, status: TransactionStatus.FINALIZED })");
      lines.push(`  return client.writeContract({ address: CONTRACT_ADDRESS, functionName: "${name}", args: [${argsList}] });`);
    } else {
      lines.push(`  const result = await client.readContract({ address: CONTRACT_ADDRESS, functionName: "${name}", args: [${argsList}] });`);
      lines.push("  return result as unknown as NonNullable<typeof result>;");
    }
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}

function chainImportPy(network: string): string {
  const map: Record<string, string> = {
    studionet: "studionet",
    "testnet-bradbury": "testnet_bradbury",
    "testnet-asimov": "testnet_asimov",
    localnet: "localnet",
  };
  return map[network] || "studionet";
}

export function generateIndexPy(schema: ContractSchema, contractAddress: string, networkName: string): string {
  const methods = Object.entries(schema.methods || {});
  const chain = chainImportPy(networkName);

  const lines: string[] = [];
  lines.push('"""Generated by GenKit — do not edit by hand.');
  lines.push(`Source: ${contractAddress} (${networkName})`);
  lines.push('"""');
  lines.push("from typing import Any, Dict, List, Optional");
  lines.push("");
  lines.push("from genlayer_py import create_client");
  lines.push(`from genlayer_py.chains import ${chain}`);
  lines.push("");
  lines.push(`CONTRACT_ADDRESS = "${contractAddress}"`);
  lines.push(`NETWORK = "${networkName}"`);
  lines.push("");
  lines.push("def get_client(endpoint: Optional[str] = None, account=None):");
  lines.push(`    return create_client(chain=${chain}, endpoint=endpoint, account=account)`);
  lines.push("");
  for (const [name, method] of methods) {
    const params = methodParams(method);
    const isWrite = method.readonly === false;
    const paramDecl = params.map((p) => `${p.name}: ${pyType(p.type)}`).join(", ");
    const argsList = params.map((p) => p.name).join(", ");
    lines.push(`def ${name}(client, ${paramDecl}${isWrite ? ", account=None" : ""}):`);
    lines.push(`    """${name} — ${isWrite ? "write" : "view"} method."""`);
    if (isWrite) {
      lines.push(`    return client.write_contract(CONTRACT_ADDRESS, "${name}", account=account, args=[${argsList}])`);
    } else {
      lines.push(`    return client.read_contract(CONTRACT_ADDRESS, "${name}", [${argsList}])`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
