import { camelCase, methodParams, tsType } from "./types.js";

export function generateSdkReadme(schema, contractAddress, networkName) {
  const methods = Object.entries(schema.methods || {});
  const views = methods.filter(([, m]) => m.readonly !== false);
  const writes = methods.filter(([, m]) => m.readonly === false);

  const lines = [];
  lines.push(`# Generated SDK — ${contractAddress}`);
  lines.push("");
  lines.push(`Auto-generated by **GenKit** from the on-chain schema of contract`);
  lines.push(`\`${contractAddress}\` on **${networkName}**.`);
  lines.push("");
  lines.push("## Install");
  lines.push("");
  lines.push("```bash");
  lines.push("npm install genlayer-js");
  lines.push("```");
  lines.push("");
  lines.push("## Usage (TypeScript)");
  lines.push("");
  lines.push("```ts");
  lines.push('import { createContractClient, CONTRACT_ADDRESS, getConfig } from "./index";');
  lines.push("const client = createContractClient();");
  lines.push("const result = await getConfig(client);");
  lines.push("```");
  lines.push("");
  lines.push("Write methods return a transaction hash. Wait for finality before reading state:");
  lines.push("");
  lines.push("```ts");
  lines.push('import { TransactionStatus } from "genlayer-js/types";');
  lines.push('import { createContractClient, registerSource } from "./index";');
  lines.push("const client = createContractClient({ account: walletAddress });");
  lines.push("const hash = await registerSource(client, \"Docs\", \"desc\", \"https://example.com\");");
  lines.push('await client.waitForTransactionReceipt({ hash, status: TransactionStatus.FINALIZED });');
  lines.push("```");
  lines.push("");
  lines.push("## Usage (Python)");
  lines.push("");
  lines.push("```python");
  lines.push('from index import get_client, get_config');
  lines.push("client = get_client()");
  lines.push("result = get_config(client)");
  lines.push("```");
  lines.push("");
  lines.push("## Methods");
  lines.push("");
  if (views.length) {
    lines.push(`**Views (${views.length})**`);
    lines.push("");
    for (const [name, method] of views) {
      const fn = camelCase(name);
      const params = methodParams(method);
      const sig = params.map((p) => `${p.name}: ${tsType(p.type)}`).join(", ");
      lines.push(`- \`${fn}(${sig})\` → \`${tsType(method.ret)}\``);
    }
    lines.push("");
  }
  if (writes.length) {
    lines.push(`**Writes (${writes.length})**`);
    lines.push("");
    for (const [name, method] of writes) {
      const fn = camelCase(name);
      const params = methodParams(method);
      const sig = params.map((p) => `${p.name}: ${tsType(p.type)}`).join(", ");
      lines.push(`- \`${fn}(${sig})\` → \`Promise<string>\` (tx hash)${method.payable ? " — payable" : ""}`);
    }
    lines.push("");
  }
  lines.push("> Regenerate with: `npx genkit generate --contract <address> --network <network> --out .`");
  lines.push("");
  return lines.join("\n");
}
