import { camelCase, methodParams, tsType } from "./types.js";

export function generateTypesTs(schema) {
  const methods = Object.entries(schema.methods || {});
  const lines = [];
  lines.push("// Generated by GenKit — do not edit by hand.");
  lines.push("export type Address = `0x${string}`;");
  lines.push("");
  for (const [name, method] of methods) {
    const fn = camelCase(name);
    const params = methodParams(method);
    lines.push(`export interface ${fn[0].toUpperCase() + fn.slice(1)}Args {`);
    for (const p of params) {
      lines.push(`  ${p.name}: ${tsType(p.type)};`);
    }
    lines.push("}");
    lines.push("");
  }
  lines.push("export type ContractSchema = {");
  lines.push("  readonly: Record<string, unknown>;");
  lines.push("  write: Record<string, unknown>;");
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

export function generateIndexTs(schema, contractAddress, networkName) {
  const methods = Object.entries(schema.methods || {});
  const chainImport = {
    studionet: "studionet",
    "testnet-bradbury": "testnetBradbury",
    "testnet-asimov": "testnetAsimov",
    localnet: "localnet",
  }[networkName] || "studionet";

  const lines = [];
  lines.push("// Generated by GenKit — do not edit by hand.");
  lines.push(`// Source: ${contractAddress} (${networkName})`);
  lines.push('import { createClient } from "genlayer-js";');
  lines.push(`import { ${chainImport} } from "genlayer-js/chains";`);
  lines.push("");
  lines.push('export type Address = `0x${string}`;');
  lines.push("");
  lines.push("export interface ContractClientOptions {");
  lines.push("  endpoint?: string;");
  lines.push("  account?: Address;");
  lines.push("  provider?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export function createContractClient(opts: ContractClientOptions = {}) {");
  lines.push("  return createClient({");
  lines.push(`    chain: ${chainImport},`);
  lines.push("    ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),");
  lines.push("    ...(opts.account ? { account: opts.account as `0x${string}` } : {}),");
  lines.push("    ...(opts.provider ? { provider: opts.provider as never } : {}),");
  lines.push("  });");
  lines.push("}");
  lines.push("");
  lines.push(`export const CONTRACT_ADDRESS = "${contractAddress}" as const;`);
  lines.push("");
  for (const [name, method] of methods) {
    const fn = camelCase(name);
    const params = methodParams(method);
    const isWrite = method.readonly === false;
    const ret = isWrite ? "string" : tsType(method.ret);
    const paramDecl = ["client", ...params.map((p) => `${p.name}: ${tsType(p.type)}`)].join(", ");
    const argsList = params.map((p) => p.name).join(", ");
    lines.push("// ─────────────────────────────────────────────");
    lines.push(`// ${name} — ${isWrite ? "write" : "view"}`);
    lines.push(`export async function ${fn}(${paramDecl}): Promise<${ret}> {`);
    if (isWrite) {
      lines.push("  // Write methods submit a transaction and return the tx hash.");
      lines.push("  // Wait for finality with: await client.waitForTransactionReceipt({ hash, status: TransactionStatus.FINALIZED })");
      lines.push(`  return client.writeContract({ address: CONTRACT_ADDRESS, functionName: "${name}", args: [${argsList}] });`);
    } else {
      lines.push(`  const result = await client.readContract({ address: CONTRACT_ADDRESS, functionName: "${name}", args: [${argsList}] });`);
      lines.push("  return result as unknown as NonNullable<typeof result>;");
    }
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}
