import { methodParams, pyType } from "./types.js";

export function generateIndexPy(schema, contractAddress, networkName) {
  const methods = Object.entries(schema.methods || {});
  const chainImport = {
    studionet: "studionet",
    "testnet-bradbury": "testnet_bradbury",
    "testnet-asimov": "testnet_asimov",
    localnet: "localnet",
  }[networkName] || "studionet";

  const lines = [];
  lines.push('"""Generated by GenKit — do not edit by hand.');
  lines.push(`Source: ${contractAddress} (${networkName})`);
  lines.push('"""');
  lines.push("from typing import Any, Dict, List, Optional");
  lines.push("");
  lines.push("from genlayer_py import create_client");
  lines.push(`from genlayer_py.chains import ${chainImport}`);
  lines.push("");
  lines.push(`CONTRACT_ADDRESS = "${contractAddress}"`);
  lines.push(`NETWORK = "${networkName}"`);
  lines.push("");
  lines.push("def get_client(endpoint: Optional[str] = None, account=None):");
  lines.push(`    return create_client(chain=${chainImport}, endpoint=endpoint, account=account)`);
  lines.push("");
  for (const [name, method] of methods) {
    const params = methodParams(method);
    const isWrite = method.readonly === false;
    const paramDecl = params.map((p) => `${p.name}: ${pyType(p.type)}`).join(", ");
    const argsList = params.map((p) => p.name).join(", ");
    lines.push(`def ${name}(client, ${paramDecl}${isWrite ? ", account=None" : ""}):`);
    lines.push(`    """${name} — ${isWrite ? "write" : "view"} method."""`);
    if (isWrite) {
      lines.push(`    return client.write_contract(CONTRACT_ADDRESS, "${name}", account=account, args=[${argsList}])`);
    } else {
      lines.push(`    return client.read_contract(CONTRACT_ADDRESS, "${name}", [${argsList}])`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
